package org.pmp.vo;

// Generated 2012-6-20 13:11:21 by Hibernate Tools 3.4.0.CR1

/**
 * BuilFeeRate generated by hbm2java
 */
public class BuilFeeRate implements java.io.Serializable {

    private Integer bfrId;
    private Building building;
    private ElectricFeeItem electricFeeItem;
    private Integer beginFloor;
    private Integer endFloor;
    private Double rate;

    public BuilFeeRate() {
    }

    public BuilFeeRate(Integer bfrId, Building building) {
	this.bfrId = bfrId;
	this.building = building;
    }

    public BuilFeeRate(Integer bfrId, Building building, Integer beginFloor,
	    Integer endFloor, double rate,ElectricFeeItem electricFeeItem) {
	this.bfrId = bfrId;
	this.building = building;
	this.electricFeeItem = electricFeeItem;
	this.beginFloor = beginFloor;
	this.endFloor = endFloor;
	this.rate = rate;
    }

    public Integer getBfrId() {
	return this.bfrId;
    }

    public void setBfrId(Integer bfrId) {
	this.bfrId = bfrId;
    }

    public Integer getBeginFloor() {
	return this.beginFloor;
    }

    public void setBeginFloor(Integer beginFloor) {
	this.beginFloor = beginFloor;
    }

    public Integer getEndFloor() {
	return this.endFloor;
    }

    public void setEndFloor(Integer endFloor) {
	this.endFloor = endFloor;
    }

    public Building getBuilding() {
        return building;
    }

    public void setBuilding(Building building) {
        this.building = building;
    }

    public ElectricFeeItem getElectricFeeItem() {
        return electricFeeItem;
    }

    public void setElectricFeeItem(ElectricFeeItem electricFeeItem) {
        this.electricFeeItem = electricFeeItem;
    }

    public Double getRate() {
        return rate;
    }

    public void setRate(Double rate) {
        this.rate = rate;
    }

}
