package org.pmp.vo;

// Generated 2012-7-3 17:31:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Complaint generated by hbm2java
 */
public class Complaint implements java.io.Serializable {

    private Integer compId;
    private HouseOwner houseOwner;
    private String compPerson;
    private String compTel;
    private Date compTime;
    private String compContent;
    private String handleResult;
    private String handlePerson;
    private Date handleTime;

    public String toString(){
	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+compId+","+houseOwner+","+compPerson+","+compTel+","+compTime+","+compContent+","+handleResult+","+
    		handlePerson+","+handleTime+"]");
    	return sb.toString();
    		
    }
    
    public Complaint() {
    }

    public Complaint(Integer compId, HouseOwner houseOwner, String compPerson,
	    String compTel, Date compTime, String compContent,
	    String handleResult, String handlePerson, Date handleTime) {
	this.compId = compId;
	this.houseOwner = houseOwner;
	this.compPerson = compPerson;
	this.compTel = compTel;
	this.compTime = compTime;
	this.compContent = compContent;
	this.handleResult = handleResult;
	this.handlePerson = handlePerson;
	this.handleTime = handleTime;
    }

    public Integer getCompId() {
	return this.compId;
    }

    public void setCompId(Integer compId) {
	this.compId = compId;
    }

    public HouseOwner getHouseOwner() {
	return this.houseOwner;
    }

    public void setHouseOwner(HouseOwner houseOwner) {
	this.houseOwner = houseOwner;
    }

    public String getCompPerson() {
	return this.compPerson;
    }

    public void setCompPerson(String compPerson) {
	this.compPerson = compPerson;
    }

    public String getCompTel() {
	return this.compTel;
    }

    public void setCompTel(String compTel) {
	this.compTel = compTel;
    }

    public Date getCompTime() {
	return this.compTime;
    }

    public void setCompTime(Date compTime) {
	this.compTime = compTime;
    }

    public String getCompContent() {
	return this.compContent;
    }

    public void setCompContent(String compContent) {
	this.compContent = compContent;
    }

    public String getHandleResult() {
	return this.handleResult;
    }

    public void setHandleResult(String handleResult) {
	this.handleResult = handleResult;
    }

    public String getHandlePerson() {
	return this.handlePerson;
    }

    public void setHandlePerson(String handlePerson) {
	this.handlePerson = handlePerson;
    }

    public Date getHandleTime() {
	return this.handleTime;
    }

    public void setHandleTime(Date handleTime) {
	this.handleTime = handleTime;
    }

}
