package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CondoFee generated by hbm2java
 */
public class CondoFee implements java.io.Serializable {

    private Integer cfId;
    private CondoFeeItem condoFeeItem;
    private House house;
    private Owner owner;
    private Date startDate;
    private Date endDate;
    private Date fetchDate;
    private Integer condoFeeRate;
    private Integer oughtMoney;
    private Integer fetchMoney;
    private String fetchTicket;
    private String fetchPerson;
    private String recordPerson;
    private String auditPerson;
    private String state;
    private Date generateTime;
    private Date inputTime;
    private Date auditTime;
    private Boolean issend;

    public CondoFee() {
    }

    public CondoFee(Integer cfId) {
	this.cfId = cfId;
    }

    public CondoFee(Integer cfId, CondoFeeItem condoFeeItem, House house,
	    Owner owner, Date startDate, Date endDate, Date fetchDate,
	    Integer condoFeeRate, Integer oughtMoney, Integer fetchMoney,
	    String fetchTicket, String fetchPerson, String recordPerson,
	    String auditPerson, String state, Date generateTime,
	    Date inputTime, Date auditTime, Boolean issend) {
	this.cfId = cfId;
	this.condoFeeItem = condoFeeItem;
	this.house = house;
	this.owner = owner;
	this.startDate = startDate;
	this.endDate = endDate;
	this.fetchDate = fetchDate;
	this.condoFeeRate = condoFeeRate;
	this.oughtMoney = oughtMoney;
	this.fetchMoney = fetchMoney;
	this.fetchTicket = fetchTicket;
	this.fetchPerson = fetchPerson;
	this.recordPerson = recordPerson;
	this.auditPerson = auditPerson;
	this.state = state;
	this.generateTime = generateTime;
	this.inputTime = inputTime;
	this.auditTime = auditTime;
	this.issend = issend;
    }

    public Integer getCfId() {
	return this.cfId;
    }

    public void setCfId(Integer cfId) {
	this.cfId = cfId;
    }

    public CondoFeeItem getCondoFeeItem() {
	return this.condoFeeItem;
    }

    public void setCondoFeeItem(CondoFeeItem condoFeeItem) {
	this.condoFeeItem = condoFeeItem;
    }

    public House getHouse() {
	return this.house;
    }

    public void setHouse(House house) {
	this.house = house;
    }

    public Owner getOwner() {
	return this.owner;
    }

    public void setOwner(Owner owner) {
	this.owner = owner;
    }

    public Date getStartDate() {
	return this.startDate;
    }

    public void setStartDate(Date startDate) {
	this.startDate = startDate;
    }

    public Date getEndDate() {
	return this.endDate;
    }

    public void setEndDate(Date endDate) {
	this.endDate = endDate;
    }

    public Date getFetchDate() {
	return this.fetchDate;
    }

    public void setFetchDate(Date fetchDate) {
	this.fetchDate = fetchDate;
    }

    public Integer getCondoFeeRate() {
	return this.condoFeeRate;
    }

    public void setCondoFeeRate(Integer condoFeeRate) {
	this.condoFeeRate = condoFeeRate;
    }

    public Integer getOughtMoney() {
	return this.oughtMoney;
    }

    public void setOughtMoney(Integer oughtMoney) {
	this.oughtMoney = oughtMoney;
    }

    public Integer getFetchMoney() {
	return this.fetchMoney;
    }

    public void setFetchMoney(Integer fetchMoney) {
	this.fetchMoney = fetchMoney;
    }

    public String getFetchTicket() {
	return this.fetchTicket;
    }

    public void setFetchTicket(String fetchTicket) {
	this.fetchTicket = fetchTicket;
    }

    public String getFetchPerson() {
	return this.fetchPerson;
    }

    public void setFetchPerson(String fetchPerson) {
	this.fetchPerson = fetchPerson;
    }

    public String getRecordPerson() {
	return this.recordPerson;
    }

    public Boolean getIssend() {
        return issend;
    }

    public void setIssend(Boolean issend) {
        this.issend = issend;
    }

    public void setRecordPerson(String recordPerson) {
	this.recordPerson = recordPerson;
    }

    public String getAuditPerson() {
	return this.auditPerson;
    }

    public void setAuditPerson(String auditPerson) {
	this.auditPerson = auditPerson;
    }

    public String getState() {
	return this.state;
    }

    public void setState(String state) {
	this.state = state;
    }

    public Date getGenerateTime() {
	return this.generateTime;
    }

    public void setGenerateTime(Date generateTime) {
	this.generateTime = generateTime;
    }

    public Date getInputTime() {
	return this.inputTime;
    }

    public void setInputTime(Date inputTime) {
	this.inputTime = inputTime;
    }

    public Date getAuditTime() {
	return this.auditTime;
    }

    public void setAuditTime(Date auditTime) {
	this.auditTime = auditTime;
    }

}
