package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CondoFeeItem generated by hbm2java
 */
public class CondoFeeItem implements java.io.Serializable {
    
    private Integer cfiId;
    private Project project;
    private Integer itemYear;
    private String itemMonth;
    private Date generateTime;
    private String generatePerson;

    public CondoFeeItem() {
    }

    public CondoFeeItem(Integer cfiId) {
	this.cfiId = cfiId;
    }

    public CondoFeeItem(Integer cfiId, Integer itemYear,
	    String itemMonth, Date generateTime, String generatePerson) {
	this.cfiId = cfiId;
	this.itemYear = itemYear;
	this.itemMonth = itemMonth;
	this.generateTime = generateTime;
	this.generatePerson = generatePerson;
    }

    public Integer getCfiId() {
	return this.cfiId;
    }

    public void setCfiId(Integer cfiId) {
	this.cfiId = cfiId;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public Integer getItemYear() {
	return this.itemYear;
    }

    public void setItemYear(Integer itemYear) {
	this.itemYear = itemYear;
    }
    
    public String getItemMonth() {
        return itemMonth;
    }

    public Date getGenerateTime() {
	return this.generateTime;
    }

    public void setGenerateTime(Date generateTime) {
	this.generateTime = generateTime;
    }

    public String getGeneratePerson() {
        return generatePerson;
    }

    public void setGeneratePerson(String generatePerson) {
        this.generatePerson = generatePerson;
    }

    public void setItemMonth(String itemMonth) {
        this.itemMonth = itemMonth;
    }
}

