package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CondoFee generated by hbm2java
 */
public class CondoFee implements java.io.Serializable {

    private Integer cfId;
    private CondoFeeItem condoFeeItem;
    private House house;
    private Owner owner;
    private Integer cfYear;
    private Integer cfMonth;
    private Date fetchDate;
    private Double condoFeeRate;
    private Double oughtMoney;
    private Double fetchMoney;
    private String fetchTicket;
    private String fetchPerson;
    private String recordPerson;
    private String auditPerson;
    private String state;
    private Date generateTime;
    private Date inputTime;
    private Date auditTime;
    private Boolean issend;

    public CondoFee() {
    }

    public CondoFee(Integer cfId) {
	this.cfId = cfId;
    }

    public CondoFee(Integer cfId, CondoFeeItem condoFeeItem, House house,
	    Owner owner, Integer cfYear, Integer cfMonth, Date fetchDate,
	    Double condoFeeRate, Double oughtMoney, Double fetchMoney,
	    String fetchTicket, String fetchPerson, String recordPerson,
	    String auditPerson, String state, Date generateTime,
	    Date inputTime, Date auditTime, Boolean issend) {
	this.cfId = cfId;
	this.condoFeeItem = condoFeeItem;
	this.house = house;
	this.owner = owner;
	this.cfYear = cfYear;
	this.cfMonth = cfMonth;
	this.fetchDate = fetchDate;
	this.condoFeeRate = condoFeeRate;
	this.oughtMoney = oughtMoney;
	this.fetchMoney = fetchMoney;
	this.fetchTicket = fetchTicket;
	this.fetchPerson = fetchPerson;
	this.recordPerson = recordPerson;
	this.auditPerson = auditPerson;
	this.state = state;
	this.generateTime = generateTime;
	this.inputTime = inputTime;
	this.auditTime = auditTime;
	this.issend = issend;
    }

    public Integer getCfId() {
	return this.cfId;
    }

    public void setCfId(Integer cfId) {
	this.cfId = cfId;
    }

    public CondoFeeItem getCondoFeeItem() {
	return this.condoFeeItem;
    }

    public void setCondoFeeItem(CondoFeeItem condoFeeItem) {
	this.condoFeeItem = condoFeeItem;
    }

    public House getHouse() {
	return this.house;
    }

    public void setHouse(House house) {
	this.house = house;
    }

    public Owner getOwner() {
	return this.owner;
    }

    public void setOwner(Owner owner) {
	this.owner = owner;
    }

    public Date getFetchDate() {
	return this.fetchDate;
    }

    public void setFetchDate(Date fetchDate) {
	this.fetchDate = fetchDate;
    }

    public String getFetchTicket() {
	return this.fetchTicket;
    }

    public void setFetchTicket(String fetchTicket) {
	this.fetchTicket = fetchTicket;
    }

    public String getFetchPerson() {
	return this.fetchPerson;
    }

    public void setFetchPerson(String fetchPerson) {
	this.fetchPerson = fetchPerson;
    }

    public Integer getCfYear() {
        return cfYear;
    }

    public void setCfYear(Integer cfYear) {
        this.cfYear = cfYear;
    }

    public Integer getCfMonth() {
        return cfMonth;
    }

    public void setCfMonth(Integer cfMonth) {
        this.cfMonth = cfMonth;
    }

    public Double getCondoFeeRate() {
        return condoFeeRate;
    }

    public void setCondoFeeRate(Double condoFeeRate) {
        this.condoFeeRate = condoFeeRate;
    }

    public Double getOughtMoney() {
        return oughtMoney;
    }

    public void setOughtMoney(Double oughtMoney) {
        this.oughtMoney = oughtMoney;
    }

    public Double getFetchMoney() {
        return fetchMoney;
    }

    public void setFetchMoney(Double fetchMoney) {
        this.fetchMoney = fetchMoney;
    }

    public String getRecordPerson() {
	return this.recordPerson;
    }

    public Boolean getIssend() {
        return issend;
    }

    public void setIssend(Boolean issend) {
        this.issend = issend;
    }

    public void setRecordPerson(String recordPerson) {
	this.recordPerson = recordPerson;
    }

    public String getAuditPerson() {
	return this.auditPerson;
    }

    public void setAuditPerson(String auditPerson) {
	this.auditPerson = auditPerson;
    }

    public String getState() {
	return this.state;
    }

    public void setState(String state) {
	this.state = state;
    }

    public Date getGenerateTime() {
	return this.generateTime;
    }

    public void setGenerateTime(Date generateTime) {
	this.generateTime = generateTime;
    }

    public Date getInputTime() {
	return this.inputTime;
    }

    public void setInputTime(Date inputTime) {
	this.inputTime = inputTime;
    }

    public Date getAuditTime() {
	return this.auditTime;
    }

    public void setAuditTime(Date auditTime) {
	this.auditTime = auditTime;
    }

}
