package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CondoFeeItem generated by hbm2java
 */
public class CondoFeeItem implements java.io.Serializable {

    private Integer cfiId;
    private Project project;
    private String itemName;
    private Integer itemYear;
    private Integer itemMonth;
    private Date generateTime;

    public CondoFeeItem() {
    }

    public CondoFeeItem(Integer cfiId) {
	this.cfiId = cfiId;
    }

    public CondoFeeItem(Integer cfiId, String itemName, Integer itemYear,
	    Integer itemMonth, Date generateTime) {
	this.cfiId = cfiId;
	this.itemName = itemName;
	this.itemYear = itemYear;
	this.itemMonth = itemMonth;
	this.generateTime = generateTime;
    }

    public Integer getCfiId() {
	return this.cfiId;
    }

    public void setCfiId(Integer cfiId) {
	this.cfiId = cfiId;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public String getItemName() {
	return this.itemName;
    }

    public void setItemName(String itemName) {
	this.itemName = itemName;
    }

    public Integer getItemYear() {
	return this.itemYear;
    }

    public void setItemYear(Integer itemYear) {
	this.itemYear = itemYear;
    }

    public Integer getItemMonth() {
	return this.itemMonth;
    }

    public void setItemMonth(Integer itemMonth) {
	this.itemMonth = itemMonth;
    }

    public Date getGenerateTime() {
	return this.generateTime;
    }

    public void setGenerateTime(Date generateTime) {
	this.generateTime = generateTime;
    }
}

