package org.pmp.vo;

// Generated 2012-6-20 13:11:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ElectricFeeItem generated by hbm2java
 */
public class ElectricFeeItem implements java.io.Serializable {

    private Integer efiId;
    private Project project;
    private String itemName;
    private Date beginDate;
    private Date endDate;
    private Date generateTime;
    private String generatePerson;
    private Double totalMoney;
    private String comment;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+efiId+","+project+","+itemName+","+beginDate+","+endDate+","+generateTime);
    	sb.append(","+generatePerson+","+totalMoney+","+comment);
    	sb.append(" ]");
    	return sb.toString();
    }
    
    public ElectricFeeItem() {
    }

    public ElectricFeeItem(Integer efiId) {
	this.efiId = efiId;
    }

    public ElectricFeeItem(Integer efiId, Project project, String itemName,
	    Date beginDate, Date endDate, Date generateTime,
	    String generatePerson, Double totalMoney, String comment) {
	this.efiId = efiId;
	this.project = project;
	this.itemName = itemName;
	this.beginDate = beginDate;
	this.endDate = endDate;
	this.generateTime = generateTime;
	this.generatePerson = generatePerson;
	this.totalMoney = totalMoney;
	this.comment = comment;
    }

    public Integer getEfiId() {
	return this.efiId;
    }

    public void setEfiId(Integer efiId) {
	this.efiId = efiId;
    }


    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public String getItemName() {
	return this.itemName;
    }

    public void setItemName(String itemName) {
	this.itemName = itemName;
    }

    public Date getBeginDate() {
	return this.beginDate;
    }

    public void setBeginDate(Date beginDate) {
	this.beginDate = beginDate;
    }

    public Date getEndDate() {
	return this.endDate;
    }

    public void setEndDate(Date endDate) {
	this.endDate = endDate;
    }

    public Date getGenerateTime() {
	return this.generateTime;
    }

    public void setGenerateTime(Date generateTime) {
	this.generateTime = generateTime;
    }

    public String getGeneratePerson() {
	return this.generatePerson;
    }

    public void setGeneratePerson(String generatePerson) {
	this.generatePerson = generatePerson;
    }

    public Double getTotalMoney() {
	return this.totalMoney;
    }

    public void setTotalMoney(Double totalMoney) {
	this.totalMoney = totalMoney;
    }

    public String getComment() {
	return this.comment;
    }

    public void setComment(String comment) {
	this.comment = comment;
    }

}
