package org.pmp.vo;

import java.util.Date;

// Generated 2012-5-21 12:04:16 by Hibernate Tools 3.4.0.CR1

/**
 * Zone generated by hbm2java
 */
public class FireDevice implements java.io.Serializable {

	private Integer fireDeviceId;
	private Zone zone;
	private String deviceNumber;
	private String typeName;
	private String mark;

	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[ " + fireDeviceId + "," + zone + "," + deviceNumber + ","
				+ typeName + "," + mark + " ]");
		return sb.toString();
	}

	public FireDevice() {
	}

	public FireDevice(Integer fireDeviceId) {
		this.fireDeviceId = fireDeviceId;
	}

	public FireDevice(Integer fireDeviceId, Zone zone, String deviceNumber,
			String typeName, String mark) {
		this.fireDeviceId = fireDeviceId;
		this.zone = zone;
		this.deviceNumber = deviceNumber;
		this.typeName = typeName;
		this.mark = mark;
	}

	public Integer getFireDeviceId() {
		return fireDeviceId;
	}

	public void setFireDeviceId(Integer fireDeviceId) {
		this.fireDeviceId = fireDeviceId;
	}

	public Zone getZone() {
		return zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

	public String getDeviceNumber() {
		return deviceNumber;
	}

	public void setDeviceNumber(String deviceNumber) {
		this.deviceNumber = deviceNumber;
	}

	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getMark() {
		return mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

}
