package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FixedParkFeeItem generated by hbm2java
 */
public class FixedParkFeeItem implements java.io.Serializable {

    private Integer fpfiId;
    private Project project;
    private String itemName;
    private Integer itemYear;
    private Integer itemMonth;
    private Date generateTime;

    public FixedParkFeeItem() {
    }

    public FixedParkFeeItem(Integer fpfiId) {
	this.fpfiId = fpfiId;
    }

    public FixedParkFeeItem(Integer fpfiId, Project project, String itemName,
	    Integer itemYear, Integer itemMonth, Date generateTime) {
	this.fpfiId = fpfiId;
	this.project = project;
	this.itemName = itemName;
	this.itemYear = itemYear;
	this.itemMonth = itemMonth;
	this.generateTime = generateTime;
    }

    public Integer getFpfiId() {
	return this.fpfiId;
    }

    public void setFpfiId(Integer fpfiId) {
	this.fpfiId = fpfiId;
    }

    public Project getProject() {
	return this.project;
    }

    public void setProject(Project project) {
	this.project = project;
    }

    public String getItemName() {
	return this.itemName;
    }

    public void setItemName(String itemName) {
	this.itemName = itemName;
    }

    public Integer getItemYear() {
	return this.itemYear;
    }

    public void setItemYear(Integer itemYear) {
	this.itemYear = itemYear;
    }

    public Integer getItemMonth() {
	return this.itemMonth;
    }

    public void setItemMonth(Integer itemMonth) {
	this.itemMonth = itemMonth;
    }

    public Date getGenerateTime() {
	return this.generateTime;
    }

    public void setGenerateTime(Date generateTime) {
	this.generateTime = generateTime;
    }

}
