package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1

/**
 * HouseOwner generated by hbm2java
 */
public class HouseOwner implements java.io.Serializable {

    private Integer hoId;
    private House house;
    private Owner owner;

    public String toString(){
    	StringBuilder sb = new StringBuilder();
    	sb.append("[ "+hoId+","+house+","+owner+","+owner+" ]");
        return sb.toString();
    } 
    
    public HouseOwner() {
    }

    public HouseOwner(Integer hoId) {
	this.hoId = hoId;
    }

    public HouseOwner(Integer hoId, House house, Owner owner) {
	this.hoId = hoId;
	this.house = house;
	this.owner = owner;
    }

    public Integer getHoId() {
	return this.hoId;
    }

    public void setHoId(Integer hoId) {
	this.hoId = hoId;
    }

    public House getHouse() {
	return this.house;
    }

    public void setHouse(House house) {
	this.house = house;
    }

    public Owner getOwner() {
	return this.owner;
    }

    public void setOwner(Owner owner) {
	this.owner = owner;
    }

}
