package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1


/**
 * House generated by hbm2java
 */
public class House implements java.io.Serializable {

    private Integer houseId;
    private Building building;
    private String houseNum;
    private Integer houseArea;
    private String houseDesc;
    private Integer condoFeeRate;
    private Integer cycleMonth;
    private boolean isempty;

    public House() {
    }

    public House(Integer houseId) {
	this.houseId = houseId;
    }

    public House(Integer houseId, Building building, String houseNum,
	    Integer houseArea, String houseDesc, Integer condoFeeRate,
	    Integer cycleMonth, boolean isempty) {
	this.houseId = houseId;
	this.building = building;
	this.houseNum = houseNum;
	this.houseArea = houseArea;
	this.houseDesc = houseDesc;
	this.condoFeeRate = condoFeeRate;
	this.cycleMonth = cycleMonth;
	this.isempty = isempty;
    }

    public Integer getHouseId() {
	return this.houseId;
    }

    public void setHouseId(Integer houseId) {
	this.houseId = houseId;
    }

    public Building getBuilding() {
	return this.building;
    }

    public void setBuilding(Building building) {
	this.building = building;
    }

    public String getHouseNum() {
	return this.houseNum;
    }

    public void setHouseNum(String houseNum) {
	this.houseNum = houseNum;
    }

    public Integer getHouseArea() {
	return this.houseArea;
    }

    public void setHouseArea(Integer houseArea) {
	this.houseArea = houseArea;
    }

    public String getHouseDesc() {
	return this.houseDesc;
    }

    public void setHouseDesc(String houseDesc) {
	this.houseDesc = houseDesc;
    }

    public Integer getCondoFeeRate() {
	return this.condoFeeRate;
    }

    public void setCondoFeeRate(Integer condoFeeRate) {
	this.condoFeeRate = condoFeeRate;
    }

    public Integer getCycleMonth() {
	return this.cycleMonth;
    }

    public void setCycleMonth(Integer cycleMonth) {
	this.cycleMonth = cycleMonth;
    }

    public boolean isIsempty() {
	return this.isempty;
    }

    public void setIsempty(boolean isempty) {
	this.isempty = isempty;
    }

}
