package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1


/**
 * House generated by hbm2java
 */
public class House implements java.io.Serializable {

    private Integer houseId;
    private Building building;
    private String houseNum;
    private Double houseArea;
    private String houseDesc;
    private Double condoFeeRate;
    private Integer cycleMonth;
    private boolean isempty;

    public String toString(){
       StringBuffer sb=new StringBuffer();
       sb.append("[ "+houseId+","+building+","+houseNum+","+houseArea+","+houseDesc+","+condoFeeRate+","+cycleMonth+","+isempty+" ]");
       return sb.toString();
    }
    
    public House() {
    }

    public House(Integer houseId) {
	this.houseId = houseId;
    }

    public House(Integer houseId, Building building, String houseNum,
	    Double houseArea, String houseDesc, Double condoFeeRate,
	    Integer cycleMonth, boolean isempty) {
	this.houseId = houseId;
	this.building = building;
	this.houseNum = houseNum;
	this.houseArea = houseArea;
	this.houseDesc = houseDesc;
	this.condoFeeRate = condoFeeRate;
	this.cycleMonth = cycleMonth;
	this.isempty = isempty;
    }

    public Integer getHouseId() {
	return this.houseId;
    }

    public void setHouseId(Integer houseId) {
	this.houseId = houseId;
    }

    public Building getBuilding() {
	return this.building;
    }

    public void setBuilding(Building building) {
	this.building = building;
    }

    public String getHouseNum() {
	return this.houseNum;
    }

    public void setHouseNum(String houseNum) {
	this.houseNum = houseNum;
    }

    public Double getHouseArea() {
	return this.houseArea;
    }

    public void setHouseArea(Double houseArea) {
	this.houseArea = houseArea;
    }

    public String getHouseDesc() {
	return this.houseDesc;
    }

    public void setHouseDesc(String houseDesc) {
	this.houseDesc = houseDesc;
    }

    public Double getCondoFeeRate() {
	return this.condoFeeRate;
    }

    public void setCondoFeeRate(Double condoFeeRate) {
	this.condoFeeRate = condoFeeRate;
    }

    public Integer getCycleMonth() {
	return this.cycleMonth;
    }

    public void setCycleMonth(Integer cycleMonth) {
	this.cycleMonth = cycleMonth;
    }

    public boolean isIsempty() {
	return this.isempty;
    }

    public void setIsempty(boolean isempty) {
	this.isempty = isempty;
    }

}
