package org.pmp.vo;

// Generated 2012-6-20 13:11:21 by Hibernate Tools 3.4.0.CR1

/**
 * LiftMeterItem generated by hbm2java
 */
public class LiftMeterItem implements java.io.Serializable {

    private Integer lmiId;
    private ElectricFeeItem electricFeeItem;
    private Building building;
    private Double beginDegree;
    private Double endDegree;
    private Double price;
    private Double totalMoney;
    private String comment;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+lmiId+","+electricFeeItem+","+building+","+beginDegree+","+endDegree+","+price);
    	sb.append(","+totalMoney+","+comment);
    	sb.append(" ]");
    	return sb.toString();
    }
    
    public LiftMeterItem() {
    }

    public LiftMeterItem(Integer lmiId) {
	this.lmiId = lmiId;
    }

    public LiftMeterItem(Integer lmiId, ElectricFeeItem electricFeeItem,
	    Building building, Double beginDegree, Double endDegree, Double price,
	    Double totalMoney, String comment) {
	this.lmiId = lmiId;
	this.electricFeeItem = electricFeeItem;
	this.building = building;
	this.beginDegree = beginDegree;
	this.endDegree = endDegree;
	this.price = price;
	this.totalMoney = totalMoney;
	this.comment = comment;
    }

    public Integer getLmiId() {
	return this.lmiId;
    }

    public void setLmiId(Integer lmiId) {
	this.lmiId = lmiId;
    }

    public Building getBuilding() {
        return building;
    }

    public void setBuilding(Building building) {
        this.building = building;
    }

    public ElectricFeeItem getElectricFeeItem() {
	return this.electricFeeItem;
    }

    public void setElectricFeeItem(ElectricFeeItem electricFeeItem) {
	this.electricFeeItem = electricFeeItem;
    }

    public Double getBeginDegree() {
	return this.beginDegree;
    }

    public void setBeginDegree(Double beginDegree) {
	this.beginDegree = beginDegree;
    }

    public Double getEndDegree() {
	return this.endDegree;
    }

    public void setEndDegree(Double endDegree) {
	this.endDegree = endDegree;
    }

    public Double getPrice() {
	return this.price;
    }

    public void setPrice(Double price) {
	this.price = price;
    }

    public Double getTotalMoney() {
	return this.totalMoney;
    }

    public void setTotalMoney(Double totalMoney) {
	this.totalMoney = totalMoney;
    }

    public String getComment() {
	return this.comment;
    }

    public void setComment(String comment) {
	this.comment = comment;
    }

}
