package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

    private Integer memId;
    private Owner owner;
    private String memName;
    private String memRelation;
    private String memIdentity;
    private String memPhone;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+memId+","+owner+","+memName+","+memRelation+","+memIdentity+","+memPhone+" ]");
    	return sb.toString();
    }
    
    public Member() {
    }

    public Member(Integer memId) {
	this.memId = memId;
    }

    public Member(Integer memId, Owner owner, String memName,
	    String memRelation, String memIdentity, String memPhone) {
	this.memId = memId;
	this.owner = owner;
	this.memName = memName;
	this.memRelation = memRelation;
	this.memIdentity = memIdentity;
	this.memPhone = memPhone;
    }

    public Integer getMemId() {
	return this.memId;
    }

    public void setMemId(Integer memId) {
	this.memId = memId;
    }

    public Owner getOwner() {
	return this.owner;
    }

    public void setOwner(Owner owner) {
	this.owner = owner;
    }

    public String getMemName() {
	return this.memName;
    }

    public void setMemName(String memName) {
	this.memName = memName;
    }

    public String getMemRelation() {
	return this.memRelation;
    }

    public void setMemRelation(String memRelation) {
	this.memRelation = memRelation;
    }

    public String getMemIdentity() {
	return this.memIdentity;
    }

    public void setMemIdentity(String memIdentity) {
	this.memIdentity = memIdentity;
    }

    public String getMemPhone() {
	return this.memPhone;
    }

    public void setMemPhone(String memPhone) {
	this.memPhone = memPhone;
    }

}
