package org.pmp.vo;

// Generated 2012-6-20 13:11:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OperateDetail generated by hbm2java
 */
public class OperateDetail implements java.io.Serializable {

    private Integer orId;
    private OwnerRepair ownerRepair;
    private Date operateTime;
    private String operatePerson;
    private String operateDetail;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+orId+","+ownerRepair+","+operateTime+","+operatePerson+","+operateDetail+" ]");
    	return sb.toString();
    }
    
    public OperateDetail() {
    }

    public OperateDetail(Integer orId) {
	this.orId = orId;
    }

    public OperateDetail(Integer orId, OwnerRepair ownerRepair,
	    Date operateTime, String operatePerson, String operateDetail) {
	this.orId = orId;
	this.ownerRepair = ownerRepair;
	this.operateTime = operateTime;
	this.operatePerson = operatePerson;
	this.operateDetail = operateDetail;
    }

    public Integer getOrId() {
	return this.orId;
    }

    public void setOrId(Integer orId) {
	this.orId = orId;
    }

    public OwnerRepair getOwnerRepair() {
	return this.ownerRepair;
    }

    public void setOwnerRepair(OwnerRepair ownerRepair) {
	this.ownerRepair = ownerRepair;
    }

    public Date getOperateTime() {
	return this.operateTime;
    }

    public void setOperateTime(Date operateTime) {
	this.operateTime = operateTime;
    }

    public String getOperatePerson() {
	return this.operatePerson;
    }

    public void setOperatePerson(String operatePerson) {
	this.operatePerson = operatePerson;
    }

    public String getOperateDetail() {
	return this.operateDetail;
    }

    public void setOperateDetail(String operateDetail) {
	this.operateDetail = operateDetail;
    }

}
