package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

    private Integer proId;
    private Company company;
    private String proName;
    private String proDistrict;
    private String proStreet;
    private String proAddress;
    private Date deliveryTime;
    private Integer proHouseCount;
    private String proDesc;
    private String proType;
    private Boolean fireEnabled;
    private Boolean enabled;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+proId+","+company+","+proName+","+proDistrict+","+proStreet+","+proAddress);
    	sb.append(","+deliveryTime+","+proHouseCount+","+proDesc+","+proType+","+fireEnabled+","+enabled);
    	sb.append(" ]");
    	return sb.toString();
    }
    
    public Project() {
    }

    public Project(Integer proId) {
	this.proId = proId;
    }

    public Project(Integer proId, Company company, String proName,
	    String proDistrict, String proStreet, String proAddress,
	    Date deliveryTime, Integer proHouseCount, String proDesc,
	    String proType, boolean fireEnabled, boolean enabled) {
	this.proId = proId;
	this.company = company;
	this.proName = proName;
	this.proDistrict = proDistrict;
	this.proStreet = proStreet;
	this.proAddress = proAddress;
	this.deliveryTime = deliveryTime;
	this.proHouseCount = proHouseCount;
	this.proDesc = proDesc;
	this.proType = proType;
	this.fireEnabled = fireEnabled;
	this.enabled = enabled;
    }

    public Integer getProId() {
	return this.proId;
    }

    public void setProId(Integer proId) {
	this.proId = proId;
    }

    public Company getCompany() {
	return this.company;
    }

    public void setCompany(Company company) {
	this.company = company;
    }

    public String getProName() {
	return this.proName;
    }

    public void setProName(String proName) {
	this.proName = proName;
    }

    public String getProDistrict() {
	return this.proDistrict;
    }

    public void setProDistrict(String proDistrict) {
	this.proDistrict = proDistrict;
    }

    public String getProStreet() {
	return this.proStreet;
    }

    public void setProStreet(String proStreet) {
	this.proStreet = proStreet;
    }

    public String getProAddress() {
	return this.proAddress;
    }

    public void setProAddress(String proAddress) {
	this.proAddress = proAddress;
    }

    public Date getDeliveryTime() {
	return this.deliveryTime;
    }

    public void setDeliveryTime(Date deliveryTime) {
	this.deliveryTime = deliveryTime;
    }

    public Integer getProHouseCount() {
	return this.proHouseCount;
    }

    public void setProHouseCount(Integer proHouseCount) {
	this.proHouseCount = proHouseCount;
    }

    public String getProDesc() {
	return this.proDesc;
    }

    public void setProDesc(String proDesc) {
	this.proDesc = proDesc;
    }

    public String getProType() {
	return this.proType;
    }

    public void setProType(String proType) {
	this.proType = proType;
    }

    public boolean isFireEnabled() {
	return this.fireEnabled;
    }

    public void setFireEnabled(boolean fireEnabled) {
	this.fireEnabled = fireEnabled;
    }

    public boolean isEnabled() {
	return this.enabled;
    }

    public void setEnabled(boolean enabled) {
	this.enabled = enabled;
    }
}
