package org.pmp.vo;

// Generated 2012-6-20 13:11:21 by Hibernate Tools 3.4.0.CR1

/**
 * ProMeterItem generated by hbm2java
 */
public class ProMeterItem implements java.io.Serializable {

    private Integer pmiId;
    private ElectricFeeItem electricFeeItem;
    private String pmNum;
    private Double beginDegree;
    private Double endDegree;
    private Double price;
    private Double totalMoney;
    private String comment;

    public ProMeterItem() {
    }

    public ProMeterItem(Integer pmiId) {
	this.pmiId = pmiId;
    }

    public ProMeterItem(Integer pmiId, ElectricFeeItem electricFeeItem,String pmNum,
	    Double beginDegree, Double endDegree, Double price,
	    Double totalMoney, String comment) {
	this.pmiId = pmiId;
	this.electricFeeItem = electricFeeItem;
	this.pmNum = pmNum;
	this.beginDegree = beginDegree;
	this.endDegree = endDegree;
	this.price = price;
	this.totalMoney = totalMoney;
	this.comment = comment;
    }

    public Integer getPmiId() {
	return this.pmiId;
    }

    public void setPmiId(Integer pmiId) {
	this.pmiId = pmiId;
    }

    public ElectricFeeItem getElectricFeeItem() {
	return this.electricFeeItem;
    }

    public void setElectricFeeItem(ElectricFeeItem electricFeeItem) {
	this.electricFeeItem = electricFeeItem;
    }

    public String getPmNum() {
        return pmNum;
    }

    public void setPmNum(String pmNum) {
        this.pmNum = pmNum;
    }

    public Double getBeginDegree() {
	return this.beginDegree;
    }

    public void setBeginDegree(Double beginDegree) {
	this.beginDegree = beginDegree;
    }

    public Double getEndDegree() {
	return this.endDegree;
    }

    public void setEndDegree(Double endDegree) {
	this.endDegree = endDegree;
    }

    public Double getPrice() {
	return this.price;
    }

    public void setPrice(Double price) {
	this.price = price;
    }

    public Double getTotalMoney() {
	return this.totalMoney;
    }

    public void setTotalMoney(Double totalMoney) {
	this.totalMoney = totalMoney;
    }

    public String getComment() {
	return this.comment;
    }

    public void setComment(String comment) {
	this.comment = comment;
    }

}
