package org.pmp.vo;

// Generated 2012-7-10 8:44:53 by Hibernate Tools 3.4.0.CR1

/**
 * PublicRepairItem generated by hbm2java
 */
public class PublicRepairItem implements java.io.Serializable {

    private Integer fbiId;
    private Project project;
    private String itemName;
    private String itemType;
    private String equipName;
    private String equipList;
    private String comment;

    public String toString(){
	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+fbiId+","+project+","+itemName+","+itemType+","+equipName+","+equipList+","+comment+" ]");
    	return sb.toString();
    }
    
    public PublicRepairItem() {
    }

    public PublicRepairItem(Integer fbiId) {
	this.fbiId = fbiId;
    }

    public PublicRepairItem(Integer fbiId, Project project, String itemName,
	    String itemType, String equipName, String equipList, String comment) {
	this.fbiId = fbiId;
	this.project = project;
	this.itemName = itemName;
	this.itemType = itemType;
	this.equipName = equipName;
	this.equipList = equipList;
	this.comment = comment;
    }

    public Integer getFbiId() {
	return this.fbiId;
    }

    public void setFbiId(Integer fbiId) {
	this.fbiId = fbiId;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public String getItemName() {
	return this.itemName;
    }

    public void setItemName(String itemName) {
	this.itemName = itemName;
    }

    public String getItemType() {
	return this.itemType;
    }

    public void setItemType(String itemType) {
	this.itemType = itemType;
    }

    public String getEquipName() {
	return this.equipName;
    }

    public void setEquipName(String equipName) {
	this.equipName = equipName;
    }

    public String getEquipList() {
	return this.equipList;
    }

    public void setEquipList(String equipList) {
	this.equipList = equipList;
    }

    public String getComment() {
	return this.comment;
    }

    public void setComment(String comment) {
	this.comment = comment;
    }

}
