package org.pmp.vo;

// Generated 2012-7-10 8:44:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PublicRepair generated by hbm2java
 */
public class PublicRepair implements java.io.Serializable {

    private Integer fbId;
    private PublicRepairItem publicRepairItem;
    private String equipNum;
    private Date repairDate;
    private String beginTime;
    private String endTime;
    private String repairDetail;
    private String repairType;
    private String state;
    private String dutyMan;

    public String toString(){
	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+fbId+","+publicRepairItem+","+equipNum+","+repairDate+","+beginTime+","+endTime+","+
    		repairDetail+","+repairType+","+state+","+dutyMan+"]");
    	return sb.toString();
    }
    
    public PublicRepair() {
    }

    public PublicRepair(Integer fbId) {
	this.fbId = fbId;
    }

    public PublicRepair(Integer fbId, PublicRepairItem publicRepairItem,
	    String equipNum, Date repairDate, String beginTime, String endTime,
	    String repairDetail, String repairType, String state, String dutyMan) {
	this.fbId = fbId;
	this.publicRepairItem = publicRepairItem;
	this.equipNum = equipNum;
	this.repairDate = repairDate;
	this.beginTime = beginTime;
	this.endTime = endTime;
	this.repairDetail = repairDetail;
	this.repairType = repairType;
	this.state = state;
	this.dutyMan = dutyMan;
    }

    public Integer getFbId() {
	return this.fbId;
    }

    public void setFbId(Integer fbId) {
	this.fbId = fbId;
    }

    public PublicRepairItem getPublicRepairItem() {
	return this.publicRepairItem;
    }

    public void setPublicRepairItem(PublicRepairItem publicRepairItem) {
	this.publicRepairItem = publicRepairItem;
    }

    public String getEquipNum() {
	return this.equipNum;
    }

    public void setEquipNum(String equipNum) {
	this.equipNum = equipNum;
    }

    public Date getRepairDate() {
	return this.repairDate;
    }

    public void setRepairDate(Date repairDate) {
	this.repairDate = repairDate;
    }

    public String getBeginTime() {
	return this.beginTime;
    }

    public void setBeginTime(String beginTime) {
	this.beginTime = beginTime;
    }

    public String getEndTime() {
	return this.endTime;
    }

    public void setEndTime(String endTime) {
	this.endTime = endTime;
    }

    public String getRepairDetail() {
	return this.repairDetail;
    }

    public void setRepairDetail(String repairDetail) {
	this.repairDetail = repairDetail;
    }

    public String getRepairType() {
	return this.repairType;
    }

    public void setRepairType(String repairType) {
	this.repairType = repairType;
    }

    public String getState() {
	return this.state;
    }

    public void setState(String state) {
	this.state = state;
    }

    public String getDutyMan() {
	return this.dutyMan;
    }

    public void setDutyMan(String dutyMan) {
	this.dutyMan = dutyMan;
    }

}
