package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SMS_Send generated by hbm2java
 */
public class SMSSend implements java.io.Serializable {

    private Integer smssId;
    private SMSCompany SMSCompany;
    private String smssContent;
    private String smssReceiver;
    private String smssState;
    private Date smssTime;
    private String smssPerson;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+smssId+","+SMSCompany+","+smssContent+","+smssReceiver+","+smssState+","+smssTime+","+smssPerson);
    	sb.append(" ]");
    	return sb.toString();
    }
    
    public SMSSend() {
    }

    public SMSSend(Integer smssId) {
	this.smssId = smssId;
    }

    public SMSSend(Integer smssId, SMSCompany SMSCompany,
	    String smssContent, String smssReceiver, String smssState,
	    Date smssTime, String smssPerson) {
	this.smssId = smssId;
	this.SMSCompany = SMSCompany;
	this.smssContent = smssContent;
	this.smssReceiver = smssReceiver;
	this.smssState = smssState;
	this.smssTime = smssTime;
	this.smssPerson = smssPerson;
    }

    public Integer getSmssId() {
	return this.smssId;
    }

    public void setSmssId(Integer smssId) {
	this.smssId = smssId;
    }

    public SMSCompany getSMSCompany() {
	return this.SMSCompany;
    }

    public void setSMSCompany(SMSCompany SMSCompany) {
	this.SMSCompany = SMSCompany;
    }

    public String getSmssContent() {
	return this.smssContent;
    }

    public void setSmssContent(String smssContent) {
	this.smssContent = smssContent;
    }

    public String getSmssReceiver() {
	return this.smssReceiver;
    }

    public void setSmssReceiver(String smssReceiver) {
	this.smssReceiver = smssReceiver;
    }

    public String getSmssState() {
        return smssState;
    }

    public void setSmssState(String smssState) {
        this.smssState = smssState;
    }

    public Date getSmssTime() {
	return this.smssTime;
    }

    public void setSmssTime(Date smssTime) {
	this.smssTime = smssTime;
    }

    public String getSmssPerson() {
	return this.smssPerson;
    }

    public void setSmssPerson(String smssPerson) {
	this.smssPerson = smssPerson;
    }

}
