package org.pmp.vo;

// Generated 2012-3-27 12:23:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbAuthority generated by hbm2java
 */
public class TbAuthority implements java.io.Serializable {

    private Integer authId;
    private String authName;
    private String authDesc;
    private Boolean enabled;
    private Boolean issys;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+authId+","+authName+","+authDesc+","+enabled+","+issys);
    	sb.append(" ]");
    	return sb.toString();
    }
    
    public TbAuthority() {
    }

    public TbAuthority(Integer authId) {
	this.authId = authId;
    }

    public TbAuthority(Integer authId, String authName, String authDesc,
	    boolean enabled, boolean issys) {
	this.authId = authId;
	this.authName = authName;
	this.authDesc = authDesc;
	this.enabled = enabled;
	this.issys = issys;
    }

    public Integer getAuthId() {
	return this.authId;
    }

    public void setAuthId(Integer authId) {
	this.authId = authId;
    }

    public String getAuthName() {
	return this.authName;
    }

    public void setAuthName(String authName) {
	this.authName = authName;
    }

    public String getAuthDesc() {
	return this.authDesc;
    }

    public void setAuthDesc(String authDesc) {
	this.authDesc = authDesc;
    }

    public boolean isEnabled() {
	return this.enabled;
    }

    public void setEnabled(boolean enabled) {
	this.enabled = enabled;
    }

    public boolean isIssys() {
	return this.issys;
    }

    public void setIssys(boolean issys) {
	this.issys = issys;
    }
}
