package org.pmp.vo;

// Generated 2012-3-27 12:23:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbGroup generated by hbm2java
 */
public class TbGroup implements java.io.Serializable {

    private Integer groupId;
    private String groupName;
    private String groupDesc;
    private Integer groupLevel;
    private String refDomain;
    private Integer fatherGroupId;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+groupId+","+groupName+","+groupDesc+","+groupLevel+","+refDomain+","+fatherGroupId);
    	sb.append(" ]");
    	return sb.toString();
    }
    
    public TbGroup() {
    }

    public TbGroup(Integer groupId) {
	this.groupId = groupId;
    }

    public TbGroup(Integer groupId, String groupName, String groupDesc,
	    Integer groupLevel, String refDomain, Integer fatherGroupId) {
	this.groupId = groupId;
	this.groupName = groupName;
	this.groupDesc = groupDesc;
	this.groupLevel = groupLevel;
	this.refDomain = refDomain;
	this.fatherGroupId = fatherGroupId;
    }

    public Integer getGroupId() {
	return this.groupId;
    }

    public void setGroupId(Integer groupId) {
	this.groupId = groupId;
    }

    public String getGroupName() {
	return this.groupName;
    }

    public void setGroupName(String groupName) {
	this.groupName = groupName;
    }

    public String getGroupDesc() {
	return this.groupDesc;
    }

    public void setGroupDesc(String groupDesc) {
	this.groupDesc = groupDesc;
    }

    public Integer getGroupLevel() {
	return this.groupLevel;
    }

    public void setGroupLevel(Integer groupLevel) {
	this.groupLevel = groupLevel;
    }

    public String getRefDomain() {
	return this.refDomain;
    }

    public void setRefDomain(String refDomain) {
	this.refDomain = refDomain;
    }

    public Integer getFatherGroupId() {
	return this.fatherGroupId;
    }

    public void setFatherGroupId(Integer fatherGroupId) {
	this.fatherGroupId = fatherGroupId;
    }
}
