package org.pmp.vo;

// Generated 2012-3-27 12:23:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbResource generated by hbm2java
 */
public class TbResource implements java.io.Serializable {

    private Integer resId;
    private String resName;
    private String resType;
    private String resLink;
    private String resDesc;
    private boolean enabled;
    private boolean issys;
    private Integer modId;

    public TbResource() {
    }

    public TbResource(Integer resId) {
	this.resId = resId;
    }

    public TbResource(Integer resId, String resName, String resType,
	    String resLink, String resDesc, boolean enabled, boolean issys,
	    Integer modId) {
	this.resId = resId;
	this.resName = resName;
	this.resType = resType;
	this.resLink = resLink;
	this.resDesc = resDesc;
	this.enabled = enabled;
	this.issys = issys;
	this.modId = modId;
    }

    public Integer getResId() {
	return this.resId;
    }

    public void setResId(Integer resId) {
	this.resId = resId;
    }

    public String getResName() {
	return this.resName;
    }

    public void setResName(String resName) {
	this.resName = resName;
    }

    public String getResType() {
	return this.resType;
    }

    public void setResType(String resType) {
	this.resType = resType;
    }

    public String getResLink() {
	return this.resLink;
    }

    public void setResLink(String resLink) {
	this.resLink = resLink;
    }

    public String getResDesc() {
	return this.resDesc;
    }

    public void setResDesc(String resDesc) {
	this.resDesc = resDesc;
    }

    public boolean isEnabled() {
	return this.enabled;
    }

    public void setEnabled(boolean enabled) {
	this.enabled = enabled;
    }

    public boolean isIssys() {
	return this.issys;
    }

    public void setIssys(boolean issys) {
	this.issys = issys;
    }

    public Integer getModId() {
	return this.modId;
    }

    public void setModId(Integer modId) {
	this.modId = modId;
    }
}
