package org.pmp.vo;

// Generated 2012-3-27 12:23:42 by Hibernate Tools 3.4.0.CR1

/**
 * TbRoleAuthority generated by hbm2java
 */
public class TbRoleAuthority implements java.io.Serializable {

    private Integer raId;
    private TbRole tbRole;
    private TbAuthority tbAuthority;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+raId+","+tbRole+","+tbAuthority);
    	sb.append(" ]");
    	return sb.toString();
    }
    
    public TbRoleAuthority() {
    }

    public TbRoleAuthority(Integer raId) {
	this.raId = raId;
    }

    public TbRoleAuthority(Integer raId, TbRole tbRole, TbAuthority tbAuthority) {
	this.raId = raId;
	this.tbRole = tbRole;
	this.tbAuthority = tbAuthority;
    }

    public Integer getRaId() {
	return this.raId;
    }

    public void setRaId(Integer raId) {
	this.raId = raId;
    }

    public TbRole getTbRole() {
	return this.tbRole;
    }

    public void setTbRole(TbRole tbRole) {
	this.tbRole = tbRole;
    }

    public TbAuthority getTbAuthority() {
	return this.tbAuthority;
    }

    public void setTbAuthority(TbAuthority tbAuthority) {
	this.tbAuthority = tbAuthority;
    }

}
