package org.pmp.vo;

// Generated 2012-4-19 19:37:27 by Hibernate Tools 3.4.0.CR1

/**
 * TbRoleModule generated by hbm2java
 */
public class TbRoleModule implements java.io.Serializable {

    private Integer rmId;
    private TbModule tbModule;
    private TbRole tbRole;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+rmId+","+tbModule+","+tbRole);
    	sb.append(" ]");
    	return sb.toString();
    }
    
    public TbRoleModule() {
    }

    public TbRoleModule(Integer rmId) {
	this.rmId = rmId;
    }

    public TbRoleModule(Integer rmId, TbModule tbModule, TbRole tbRole) {
	this.rmId = rmId;
	this.tbModule = tbModule;
	this.tbRole = tbRole;
    }

    public Integer getRmId() {
	return this.rmId;
    }

    public void setRmId(Integer rmId) {
	this.rmId = rmId;
    }

    public TbModule getTbModule() {
	return this.tbModule;
    }

    public void setTbModule(TbModule tbModule) {
	this.tbModule = tbModule;
    }

    public TbRole getTbRole() {
        return tbRole;
    }

    public void setTbRole(TbRole tbRole) {
        this.tbRole = tbRole;
    }
}
