package org.pmp.vo;

// Generated 2012-3-27 12:23:42 by Hibernate Tools 3.4.0.CR1

/**
 * TbUserGroupRole generated by hbm2java
 */
public class TbUserGroupRole implements java.io.Serializable {

    private Integer ugrId;
    private TbUser tbUser;
    private TbRole tbRole;
    private TbGroup tbGroup;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+ugrId+","+tbUser+","+tbRole+","+tbGroup);
    	sb.append(" ]");
    	return sb.toString();
    }
    
    public TbUserGroupRole() {
    }

    public TbUserGroupRole(Integer ugrId) {
	this.ugrId = ugrId;
    }

    public TbUserGroupRole(Integer ugrId, TbUser tbUser, TbRole tbRole,
	    TbGroup tbGroup) {
	this.ugrId = ugrId;
	this.tbUser = tbUser;
	this.tbRole = tbRole;
	this.tbGroup = tbGroup;
    }

    public Integer getUgrId() {
	return this.ugrId;
    }

    public void setUgrId(Integer ugrId) {
	this.ugrId = ugrId;
    }

    public TbUser getTbUser() {
	return this.tbUser;
    }

    public void setTbUser(TbUser tbUser) {
	this.tbUser = tbUser;
    }

    public TbRole getTbRole() {
	return this.tbRole;
    }

    public void setTbRole(TbRole tbRole) {
	this.tbRole = tbRole;
    }

    public TbGroup getTbGroup() {
	return this.tbGroup;
    }

    public void setTbGroup(TbGroup tbGroup) {
	this.tbGroup = tbGroup;
    }

}
