package org.pmp.vo;

// Generated 2012-4-19 19:48:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TimeParkFee generated by hbm2java
 */
public class TimeParkFee implements java.io.Serializable {

    private Integer tpfId;
    private Project project;
    private String carNum;
    private Date parkDate;
    private Integer parkTime;
    private double parkFeeRate;
    private double fetchMoney;
    private String fetchPerson;
    private String recordPerson;
    private Date recordTime;
    private String auditPerson;
    private Date auditTime;
    private String state;

    public String toString(){
    	StringBuffer sb=new StringBuffer();
    	sb.append("[ "+tpfId+","+project+","+carNum+","+parkDate+","+parkTime+","+parkFeeRate);
    	sb.append(","+fetchMoney+","+fetchPerson+","+recordPerson+","+recordTime+","+auditPerson+","+auditTime+","+state);
    	sb.append(" ]");
    	return sb.toString();
    }
    
    public TimeParkFee() {
    }

    public TimeParkFee(Integer tpfId) {
	this.tpfId = tpfId;
    }

    public TimeParkFee(Integer tpfId, Project project, String carNum,
	    Date parkDate, Integer parkTime, double parkFeeRate,
	    double fetchMoney, String fetchPerson, String recordPerson,
	    Date recordTime, String auditPerson, Date auditTime, String state) {
	this.tpfId = tpfId;
	this.project = project;
	this.carNum = carNum;
	this.parkDate = parkDate;
	this.parkTime = parkTime;
	this.parkFeeRate = parkFeeRate;
	this.fetchMoney = fetchMoney;
	this.fetchPerson = fetchPerson;
	this.recordPerson = recordPerson;
	this.recordTime = recordTime;
	this.auditPerson = auditPerson;
	this.auditTime = auditTime;
	this.state = state;
    }

    public Integer getTpfId() {
	return this.tpfId;
    }

    public void setTpfId(Integer tpfId) {
	this.tpfId = tpfId;
    }

    public Project getProject() {
	return this.project;
    }

    public void setProject(Project project) {
	this.project = project;
    }

    public String getCarNum() {
	return this.carNum;
    }

    public void setCarNum(String carNum) {
	this.carNum = carNum;
    }

    public Date getParkDate() {
	return this.parkDate;
    }

    public void setParkDate(Date parkDate) {
	this.parkDate = parkDate;
    }

    public Integer getParkTime() {
	return this.parkTime;
    }

    public void setParkTime(Integer parkTime) {
	this.parkTime = parkTime;
    }

    public double getParkFeeRate() {
	return this.parkFeeRate;
    }

    public void setParkFeeRate(double parkFeeRate) {
	this.parkFeeRate = parkFeeRate;
    }

    public double getFetchMoney() {
	return this.fetchMoney;
    }

    public void setFetchMoney(double fetchMoney) {
	this.fetchMoney = fetchMoney;
    }

    public String getFetchPerson() {
	return this.fetchPerson;
    }

    public void setFetchPerson(String fetchPerson) {
	this.fetchPerson = fetchPerson;
    }

    public String getRecordPerson() {
	return this.recordPerson;
    }

    public void setRecordPerson(String recordPerson) {
	this.recordPerson = recordPerson;
    }

    public Date getRecordTime() {
	return this.recordTime;
    }

    public void setRecordTime(Date recordTime) {
	this.recordTime = recordTime;
    }

    public String getAuditPerson() {
	return this.auditPerson;
    }

    public void setAuditPerson(String auditPerson) {
	this.auditPerson = auditPerson;
    }

    public Date getAuditTime() {
	return this.auditTime;
    }

    public void setAuditTime(Date auditTime) {
	this.auditTime = auditTime;
    }

    public String getState() {
	return this.state;
    }

    public void setState(String state) {
	this.state = state;
    }

}
